### ISSUE TITLE
Ponzi++

### ISSUE THREAD

**Issue by dm17** [openblockchains/bitcoin-ponzi#2]
I'd like to add a few arguments I see brushed off very often (in no particular order):

1) "BTC is limited just like Gold"

No it isn't; false comparison. You can't create more elements like gold which are of limited amount. You can create unlimited cryptocurrencies, each which is limited in its amount. And in the psychology of the user, having a lot more cryptocurrencies, at the very least, decreases the amount of confidence in any one of them.

For actual comparison, imagine if someone could invent more elements like silver & gold on the fly. Yes, it would not increase the abundance of gold - but it could easily affect the price of silver & gold!

2) Blockchain is a commodity in its utility alone, like gold

Again, blockchains can do stuff and be commoditized - but not like gold... 
Gold always conducts electricity. BTC always costs electricity. And in our currently "unrealized state of adoption" it is already costing as much power as the entire country of Ireland:
https://www.forbes.com/sites/christopherhelman/2018/01/16/bitcoin-mining-uses-as-much-power-as-ireland-and-why-thats-not-a-problem/?sh=67b91c9e4589

3) "Volatility is greater just because it is a new currency"

No... You can see the introduction of the Euro when it was a new currency - and it does not follow the pattern of any cryptocurrencies. Cryptocurrencies are in a category of their own in terms of volatility. I don't have a great reference off hand, but it seems that cryptocurrencies are an order of magnitude *more volatile* than regular fiat currencies.

4) "Hey idiot, I'm rich on BTC, so your arguments are invalid"

This isn't a logical argument. It can be ignored, but there are also so many reasons why BTC should be pupped as regular fiat currencies collapse.

5) "BTC is free from regulation, unlike fiat"

Here are a few facts, which are obviously open to interpretation:
-- Most exchanges already scan your ID
-- Most exchanges can be easily regulated by the government
-- Central banks want digital currencies
-- Talk of one world currencies has been going on for a long time
-- "Decentralized" in one way, but its code base is way *more* centralized in terms of controlling how it works
-- ... I could probably list 5 more here if there is sufficient interest

6) "BTC is only a value store; nothing wrong with that"

That is a really nice way of saying it is hard to get your money in & out. That is not evidence that BTC hasn't sufficiently tried to be a fiat replacement

7) "This saves us from a downfalls of central banks"

This provides arguments to the contrary and a lot more:
https://www.metzdowd.com/pipermail/cryptography/2020-December/036510.html

![image](https://user-images.githubusercontent.com/2621663/109873621-ab7ccc80-7c76-11eb-8198-bc6916c65b5c.png)

**Comment by geraldb** [comment]
Good points. Thanks for taking the time and sharing..  Yeah, the best argument for bitcoin is and always has been - Have fun staying poor (HFSP).     The delusion of getting rich by HODLing (doing nothing) is still strong - now the "smart money" is buying up satoshis in the ponzi...  hoping for big returns.

**Comment by dm17** [comment]
@geraldb What is the argument against Austrian economics & how it is related?

**Comment by geraldb** [comment]
The preferred "value theory" of bitcoin is the austrian school of economics subjective theory of value (money) (by Carl Menger - founder of the Austrian School of Economics) or such or claimed by bitcoiners.  In a nutshell it is as simple as "Anything has value as long as enough people believe in it - it's all subjective - in the worst case just find another great fool to sell for profit!".     A great summary you find find in Chapter 2: The Bitcoin ideology - Austrian economics  in the book(let) by David Gerard <https://davidgerard.co.uk/blockchain/table-of-contents/>.   Anyways, the point to this stupid argument is that the mining costs for the bitcoin network are very real and  environmental damage is not subjective but very objective and very real.  It's not all just subjective make believe bullshit.

[1]: <https://en.wikipedia.org/wiki/Subjective_theory_of_value>

**Comment by dm17** [comment]
> The preferred "value theory" of bitcoin is the austrian school of economics subjective theory of value (money)¹ (by Carl Menger - founder of the Austrian School of Economics) or such or claimed by bitcoiners. In a nutshell it is as simple as "Anything has value as long as enough people believe in it - it's all subjective - in the worst case just find one greater fool to sell for profit!". A great summary you can find in Chapter 2: The Bitcoin ideology - Austrian economics in the book(let) by David Gerard https://davidgerard.co.uk/blockchain/table-of-contents/. Anyways, the point to this stupid argument is that the mining costs for the bitcoin network are very real and environmental damage (co2 emissions, electronic waste, etc.) is not subjective but very objective and very real. It's not all just subjective make believe bullshit.
> 
> PS: The real case against Austrian Economics bullshit is really denying the existence of history (in studying economics) - sure history doesn't repeat itself - but claiming that the real world is wrong and the subjective theory is right is close to the "scientific" method of flat-earthers.
> 
> ¹: https://en.wikipedia.org/wiki/Subjective_theory_of_value

I agree that relativism is nonsense. However, this seems to be a good Austrian argument for not trusting cryptocurrencies. If people can be swayed to invest in something they momentarily believe has value (while having no inherent value), then such schemes would be dangerous for their monetary instability. Would take a while for us to get down to the details on this - but it sounds like if we leave out the theory and just describe the actual effects of cryptocurrency, then it is something the "left" & "right" can agree on.

**Comment by geraldb** [comment]
Sure that's the point - it is hard to deny the objective facts of the the co2 emissions and massive electronic waste - for what? For maintaining a  public database (of the size less than 1 Gigabyte). LOL.  Or how about agreeing on the 7 transactions max  per seconds and a confirmation (block) time of 10 minutes and so on. It's not all subjective.

**Comment by dm17** [comment]
> or maintaining a public database

I don't think the electronic waste is an issue. I'm not a Co2 believer. But it is a problem for "progressives" since they like (globalist) digital currency & also believe in climate collapse (opposite is true: we're about to hit a grand solar minimum and the food shortages that come with it). The better argument is it depends on electricity, which is easily controlled - and potentially unstable (just look at massive energy producer "Taxes" as of late).

We don't need to know "why" in order to observe the fact that cryptocurrency consistently has an order of magnitude more volatility than regular fiat.

**Comment by geraldb** [comment]
The high volatility of bitcoin is because it's all about speculation.     Usually forgotten - bitcoin is fiat, that is, it is all subjective - USD or EUR or such are not fiat because national currencies are legal tender and backed by the purchasing power of the economy.

**Comment by dm17** [comment]
> The high volatility of bitcoin is because it's all about speculation. Usually forgotten and contrary to popular bitcoin ideology - bitcoin is fiat, that is, it is all subjective - USD or EUR or such are not fiat because national currencies are legal tender and backed by the purchasing power of the economy.

USD is not fiat? More has printed in the last year or so than in the fiat's history, or something like that... USD is a fiat that has a lot supporting it globally. Petrodollars, for example, are pegged to petroleum production, which helps stabilize it. There are many real things that help stabilize it including the collective belief, as the Austrian system describes. Cryptocurrency is yet another detached from reality being based on fiat. Reality > real money > fiat-money > crypto-fiat... In this age of inversion, it is no wonder that is viewed in reverse order. Even crypto experts, when they say to themselves "I have 50 BTC" go to lookup on their exchange app: "ok, how much actual money is that."

Sun output is well recorded & easy to lookup. It doesn't seem you've looked into it at all.

**Comment by geraldb** [comment]
Yes, USD is NOT fiat.  It is legal tender backed by the purchasing power of the US economy.  Economics 101.

**Comment by dm17** [comment]
> Yes, USD is NOT fiat. It is legal tender backed by the purchasing power of the US economy. Economics 101.
> 
> > Sun output is well recorded & easy to lookup. It doesn't seem you've looked into it at all.
> 
> There are no records going back centuries. And without reliable data you cannot predict the future. It's just speculation. That's all.

I didn't say USD was not considered legal tender. But it seems to be a basic fact that it is also fiat. Not mutually exclusive these days... USD historically became a fiat when they were able to create more debt than money in existence. That is when it was inverted conceptually from wealth to debt.

**Comment by dm17** [comment]
> Yes, USD is NOT fiat. It is legal tender backed by the purchasing power of the US economy. Economics 101.
> 
> > Sun output is well recorded & easy to lookup. It doesn't seem you've looked into it at all.
> 
> There are no records going back centuries. And without reliable data you cannot predict the future. It's just speculation. That's all.

Within the last couple centuries, yes. Funny how that is all you need but for AGW you have fabricated evidence going back hundreds of thousands of years based on a bogus green house effect.

**Comment by geraldb** [comment]
Pumping CO2 into the atmosphere starts with the industrial revolution in England in the 18th century - no need to fabricate evidence going back hundreds of thousand years.   

I am no more confused than before - you seem to hate central banks and "fiat" money - and I may misread your criticism on the bitcoin ponzi. Anyways, have a great fun day staying poor. Cheers. Prosit 2021!
